### ISSUE TITLE
`bun create stein` command does not work as expected

### ISSUE THREAD

**Issue by trobonox** [steinjs/stein#13]
All other package managers call the create module correctly (e.g. `pnpm create stein`) and enter the "setup wizard" for scaffolding a new project instantly. Using `bun create stein` downloads the CLI but runs the wrong entrypoint which is for the main CLI.

**Comment by vexcited** [comment]
Resolved in <https://github.com/steinjs/stein/commit/20fdc67cede7ac942f8b78b80105a14c3644850b>
